var ua=navigator.userAgent,os=/iphone|ipad|ipod/gi.test(ua)?"ios":/android/gi.test(ua)?"android":/mac/gi.test(ua)?"macOS":/windows/gi.test(ua)?"Windows":"other",btnStory=document.querySelector("#btnStory"),btnKakao=document.querySelector("#btnKakao"),totalCount=0,count=1,hasTouch="ontouchstart"in window,evtStart=hasTouch?evtStart="touchstart":evtStart="mousedown",evtEnd=hasTouch?evtEnd="touchend":evtEnd="mouseup",autoId=null,isChance=!1,chanceTimeId,chanceTime,isAuto=!1,team,scoreBoy,scoreGirl,scoreSub,
round;if("ios"!=os&&"android"!=os)var adTop=document.querySelector("#adTop"),adBottom=document.querySelector("#adBottom"),adMiddle=document.querySelector("#adMiddle");
window.addEventListener("DOMContentLoaded",function(){M("#btnBoy").on("click",function(){team="boy";M("#btnStory").text("\uc624\ube60\ud300 \uc18c\ud658\ud558\uae30");M("#btnSubmit").text("\uc624\ube60\ud300 \uc810\uc218\uc804\uc1a1");gameStart()});M("#btnGirl").on("click",function(){team="girl";M("#btnStory").text("\uc5b8\ub2c8\ud300 \uc18c\ud658\ud558\uae30");M("#btnSubmit").text("\uc5b8\ub2c8\ud300 \uc810\uc218\uc804\uc1a1");gameStart()});M("#scoreBoard").on("click",function(b,c){M(".extend").hasClass("min")?
(M(".extend").removeClass("min"),M(".history").css("display","none")):(M(".extend").addClass("min"),M(".history").css("display","block"),getStatus())});btnStory.addEventListener("click",executeKakaoStoryLink,!1);btnKakao.addEventListener("click",executeURLLink,!1);getVs()},!1);
function getStatus(){var b=M.json(M.storage("io.github.romeoh.tab")),c;c="null"==b?0:(b=b["round"+round])?b:0;$.ajax({url:"http://romeoh78.appspot.com/api/vs/get/status",contentType:"text/plain",data:'{"body" : {}, "head" : {}}',type:"POST",success:function(b){b=M.json(b).body.rounds;var e=b.length-1,a;a=""+("<h3>\ub098\uc758 "+round+"\uacbd\uae30 \ud300 \uae30\uc5ec\ub3c4</h3>");a+="<p>\ucd1d "+M.toCurrency(c)+" \ud0ed \uae30\uc5ec\ud558\uc600\uc2b5\ub2c8\ub2e4.</p>";M(".myscore").html(a);a="";for(var d=
0;d<e;d++){var k=b[d].round,f=b[d].boy,g=b[d].girl,l=b[d].s_date,p=l.substr(5,2),l=l.substr(8,2),m=b[d].e_date,q=m.substr(5,2),m=m.substr(8,2),n;a+="<dl>";f>g?(n=f-g,a+="\t<dt>"+k+"\uacbd\uae30 \uc6b0\uc2b9: \uc624\ube60\ud300 ("+M.toCurrency(n)+"\ud0ed)</dt>",a+="\t<dd>\uc624\ube60\ud300: "+M.toCurrency(f)+"\ud0ed</dd>",a+="\t<dd>\uc5b8\ub2c8\ud300: "+M.toCurrency(g)+"</dd>"):(n=g-f,a+="\t<dt>"+k+"\uacbd\uae30 \uc6b0\uc2b9: \uc5b8\ub2c8\ud300 ("+M.toCurrency(n)+"\ud0ed)</dt>",a+="\t<dd>\uc5b8\ub2c8\ud300: "+
M.toCurrency(g)+"\ud0ed</dd>",a+="\t<dd>\uc624\ube60\ud300: "+M.toCurrency(f)+"\ud0ed</dd>");a+="\t<dd>\uae30\uac04: "+p+"\uc6d4 "+l+"\uc77c 04\uc2dc ~ "+q+"\uc6d4 "+m+"\uc77c 04\uc2dc</dd>";a+="</dl>"}M("#round").html(a)}})}
function getVs(){$.ajax({url:"http://romeoh78.appspot.com/api/vs/get/ing",contentType:"text/plain",data:'{"body" : {}, "head" : {}}',type:"POST",success:function(b){b=M.json(b).body;var c=b.boy,h=b.girl,e=b.s_date,a=b.e_date,d=e.substr(5,2),k=e.substr(8,2);e.substr(11,2);var e=a.substr(5,2),f=a.substr(8,2);a.substr(11,2);var a="",g=M(".extend").hasClass("min");scoreBoy=c;scoreGirl=h;round=b.round;g?(M("#scoreBoard").html(round+"\uacbd\uae30 ("+d+"\uc6d4 "+k+"\uc77c 04\uc2dc ~ "+e+"\uc6d4 "+f+'\uc77c 04\uc2dc)<span class="extend min"></span>'),
getStatus()):M("#scoreBoard").html(round+"\uacbd\uae30 ("+d+"\uc6d4 "+k+"\uc77c 04\uc2dc ~ "+e+"\uc6d4 "+f+'\uc77c 04\uc2dc)<span class="extend"></span>');c>h?(a+='<div id="reload"></div><div class="team0">',a+='\t<p class="title">\uc624\ube60\ud300 \uc2a4\ucf54\uc5b4\ubcf4\ub4dc</p>',a+='\t<p class="score">'+M.toCurrency(c)+" \ud0ed</p>",a+="</div>",a+='<div class="team1">',a+='\t<p class="title">\uc5b8\ub2c8\ud300 \uc2a4\ucf54\uc5b4\ubcf4\ub4dc</p>',a+='\t<p class="score">'+M.toCurrency(h)+" \ud0ed</p>",
a+="</div>",scoreSub=c-h,M("#info").text("\ud604\uc7ac \uc624\ube60\ud300\uc774 "+M.toCurrency(scoreSub)+"\ud0ed \uc55e\uc11c\uace0 \uc788\uc2b5\ub2c8\ub2e4.")):(a+='<div id="reload"></div>',a+='<div class="team0">',a+='\t<p class="title">\uc5b8\ub2c8\ud300 \uc2a4\ucf54\uc5b4\ubcf4\ub4dc</p>',a+='\t<p class="score">'+M.toCurrency(h)+" \ud0ed</p>",a+="</div>",a+='<div class="team1">',a+='\t<p class="title">\uc624\ube60\ud300 \uc2a4\ucf54\uc5b4\ubcf4\ub4dc</p>',a+='\t<p class="score">'+M.toCurrency(c)+
" \ud0ed</p>",a+="</div>",scoreSub=h-c,M("#info").text("\ud604\uc7ac \uc5b8\ub2c8\ud300\uc774 "+M.toCurrency(scoreSub)+"\ud0ed \uc55e\uc11c\uace0 \uc788\uc2b5\ub2c8\ub2e4."));M("#board").html(a);M("#reload").on("click",function(){M("#board").text("");M("#info").text("");getVs()})}})}
function gameStart(){M("#game").css("display","block");M("#share").css("display","block");M(".btnBoxStart").css("display","none");M("#btnClick").on(evtStart,function(){M("#btnAuto").text("\uc790\ub3d9\ud0ed");isAuto=!1;clearInterval(autoId);autoId=null;onPress()});M("#btnClick").on(evtEnd,onRelease);M("#btnAuto").on("click",onAuto);M("#btnSubmit").on("click",onSubmit)}
function onPress(b,c){b&&(b.preventDefault(),stopAuto());0==getRandom(0,100)&&chanceMode();M("#btnClick").removeClass("purple").addClass("purpleAct")}function onRelease(b,c){M("#btnClick").addClass("purple").removeClass("purpleAct");totalCount+=count;M("#counter").text(M.toCurrency(totalCount)).data("count",totalCount);14<totalCount&&M("#btnAuto").addClass("blue");19<totalCount&&M("#btnSubmit").addClass("blue")}
function chanceMode(){isChance||(isChance=!0,count=getRandom(2,10),chanceTimeId=setInterval(chanceCount,1E3),chanceTime=getRandom(3,15),setTimeout(normalMode,1E3*chanceTime),M("#btnClick").text("\ucc2c\uc2a4! \uc9c0\uae08\ubd80\ud130 "+count+"\ubc30! ("+chanceTime+"\ucd08\uac04)"))}
function chanceCount(){M("#btnClick").text("\ucc2c\uc2a4! \uc9c0\uae08\ubd80\ud130 "+count+"\ubc30! ("+chanceTime+"\ucd08\uac04)");chanceTime--;0===chanceTime&&(normalMode(),clearInterval(chanceTimeId),chanceTimeId=null)}function normalMode(){isChance=!1;count=1;M("#btnClick").text("\ud0ed! \ud0ed! \ud0ed!")}
function onAuto(b,c){if(15>totalCount)return alert("\ucd5c\uc18c 15\ud0ed \uc774\uc0c1 \ub2ec\uc131\ud574\uc57c \uc0ac\uc6a9\ud560\uc218 \uc788\uc2b5\ub2c8\ub2e4."),!1;isAuto?(c.text("\uc790\ub3d9\ud0ed"),isAuto=!1,clearInterval(autoId),autoId=null):(c.text("\uc218\ub3d9\ud0ed"),isAuto=!0,autoId=setInterval(press,200))}function press(){onPress();setTimeout(function(){onRelease()},100)}function stopAuto(){clearInterval(autoId);autoId=null}
function onSubmit(){if("ios"!=M.browser().os&&"android"!=M.browser().os)return!1;if(20>totalCount)return alert("\ucd5c\uc18c 20\ud0ed \uc774\uc0c1 \ub2ec\uc131\ud574\uc57c \uc810\uc218\ub97c \uc804\uc1a1\ud560\uc218 \uc788\uc2b5\ub2c8\ub2e4."),!1;var b={},c={},c=M.json(M.storage("io.github.romeoh.tab"));"null"===c?(c={},c["round"+round]=totalCount):(savedStorage=M.json(M.storage("io.github.romeoh.tab")),savedStorage["round"+round]?(savedData=savedStorage["round"+round],c["round"+round]=totalCount+
savedData):c["round"+round]=totalCount);M.storage("io.github.romeoh.tab",M.json(c));b.category=team;b.count=totalCount;c={body:b,head:{}};stopAuto();totalCount=0;M("#btnAuto").removeClass("blue");M("#btnSubmit").removeClass("blue");M("#counter").text("0");$.ajax({url:"http://romeoh78.appspot.com/api/vs/add",contentType:"text/plain",data:M.json(c),type:"POST",success:function(b){getVs()}})}function getRandom(b,c){return Math.floor(Math.random()*(c-b)+b)}
function executeKakaoStoryLink(){var b;b="[ \uc804\uad6d\ubbfc \ud0ed!\ud0ed!\ud0ed! ]\n\uc62c\uc5ec\ub984 \uc804\uad6d\ubbfc\uc740 \uad11\ud0ed\uc9c8(\uc131\ub300\uacb0)\uc5d0 \ube60\uc838\ub4e0\ub2e4.\n";"boy"===team?(b=scoreBoy>scoreGirl?b+("\uc9c0\uae08 \uc624\ube60\ud300\uc774 "+M.toCurrency(scoreSub)+"\ud0ed \uc55e\uc11c\uace0 \uc788\uc5b4\uc694.\n"):b+("\uc9c0\uae08 \uc624\ube60\ud300\uc774 "+M.toCurrency(scoreSub)+"\ud0ed \ub4a4\uc9c0\uace0 \uc788\uc5b4\uc694.\n"),b+="* \ud604\uc7ac\uc810\uc218 *\n",
b+="\uc624\ube60\ud300: "+M.toCurrency(scoreBoy)+"\ud0ed\n",b+="\uc5b8\ub2c8\ud300: "+M.toCurrency(scoreGirl)+"\ud0ed\n"):(b=scoreBoy>scoreGirl?b+("\uc9c0\uae08 \uc5b8\ub2c8\ud300\uc774 "+M.toCurrency(scoreSub)+"\ud0ed \ub4a4\uc9c0\uace0 \uc788\uc5b4\uc694.\n"):b+("\uc9c0\uae08 \uc5b8\ub2c8\ud300\uc774 "+M.toCurrency(scoreSub)+"\ud0ed \uc55e\uc11c\uace0 \uc788\uc5b4\uc694.\n"),b+="* \ud604\uc7ac\uc810\uc218 *\n",b+="\uc5b8\ub2c8\ud300: "+M.toCurrency(scoreGirl)+"\ud0ed\n",b+="\uc624\ube60\ud300: "+
M.toCurrency(scoreBoy)+"\ud0ed\n");b+="\ucc38\uc5ec\ud558\uae30: http://goo.gl/qYVOp\n";b="https://twitter.com/intent/tweet?text="+encodeURIComponent(b);window.location.href=b}function executeURLLink(){kakao.link("talk").send({msg:"\ud0ed!\ud0ed!\ud0ed!",url:"http://goo.gl/qIIMX",appid:"funnyApp",appver:"1.0",appname:"\ud0ed!\ud0ed!\ud0ed!",type:"link"})};